# Generated by Django 4.2.4 on 2023-10-18 10:30

import Main.api.file_path_converter
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "男"),
                            ("F", "女"),
                            ("B", "小男孩"),
                            ("G", "小女孩"),
                            ("H", "武装直升机"),
                            ("C", "沃尔玛购物袋"),
                            ("R", "RockyRoo的小狗狗"),
                            ("S", "不公开"),
                        ],
                        default="S",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "biography",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="个签"
                    ),
                ),
                (
                    "avator",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Main.api.file_path_converter.user_img_path,
                        verbose_name="头像",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
        ),
    ]
