# Generated by Django 4.2.4 on 2023-09-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FapMaster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faplog",
            name="comments",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="备注"
            ),
        ),
    ]
